services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-ws-server:latest
    container_name: node-ws-server
    ports:
      - 4000:4000
      - 4001:4001
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mongo
      - node-ws-broker
    volumes:
      - ./:/app

  mongo:
    image: mongo:latest
    container_name: node-ws-mongo-db
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    env_file:
      - .env

  node-ws-broker:
    image: rabbitmq:3-management
    container_name: node-ws-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped
    env_file:
      - .env

volumes:
  mongo-data: